local settings = require("settings")
local colors = require("colors")

--sbar.add("alias", "MeetingBar", {
-- position = "right",
-- background = {
--     color = colors.transparent,
--     border_color = colors.transparent,
--     border_width = settings.widgets.border.width
-- }
--})

---- Padding item required because of bracket
--sbar.add("item", {
--    position = "right",
--    width = settings.group_paddings
--})
--
--local cal = sbar.add("item", {
--    icon = {
--        color = colors.white,
--        padding_left = 8,
--        font = {
--            size = 22.0
--        }
--    },
--    label = {
--        color = colors.white,
--        padding_right = 8,
--        width = 80,
--        align = "right",
--        font = {
--            family = settings.icons
--        }
--    },
--    position = "right",
--    update_freq = 30,
--    padding_left = 1,
--    padding_right = 1,
--    background = {
--        color = colors.transparent,
--        border_color = colors.white,
--        border_width = 1
--    }
--})
--
---- Double border for calendar using a single item bracket
---- sbar.add("bracket", { cal.name }, {
----   background = {
----     color = colors.transparent,
----     height = 30,
----     border_color = colors.grey,
----   }
---- })
--
---- Padding item required because of bracket
--sbar.add("item", {
--    position = "right",
--    width = settings.group_paddings
--})
--
--cal:subscribe({"forced", "routine", "system_woke"}, function(env)
--    cal:set({
--        icon = "",
--        label = os.date("%m/%d %H:%M")
--    })
--end)
