require("items.widgets.battery")
sbar.add("item", { position = "right", width = 8 })
require("items.widgets.volume")
sbar.add("item", { position = "right", width = 8 })
require("items.widgets.wifi")
sbar.add("item", { position = "right", width = 8 })
require("items.widgets.cpu")
sbar.add("item", { position = "right", width = 8 })
require("items.widgets.memory")
